kind: Deployment
apiVersion: apps/v1
metadata:
  name: azuredevops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: azuredevops
  template:
    metadata:
      labels:
        app: azuredevops
    spec:
      containers:
        - name: azuredevops
          image: sona5r/loki
          imagePullPolicy: Always
          ports:
            - containerPort: 80
